### ISSUE TITLE
Feature Suggestion - Autocomplete Search

### ISSUE THREAD

**Issue by Escalion** [billycastelli/Movie-Watchlist#1]
It may be a nice feature to keep a cache of the most popular movies, and use this for 'autocomplete' when typing in the search.

Perhaps https://github.com/TarekRaafat/autoComplete.js may be a good place to start?

**Comment by billycastelli** [comment]
> It may be a nice feature to keep a cache of the most popular movies, and use this for 'autocomplete' when typing in the search.
> 
> Perhaps https://github.com/TarekRaafat/autoComplete.js may be a good place to start?

Looks pretty cool, thanks for the suggestion!
